# Select library type
option(BUILD_SHARED_LIBS "Build @PROJECT_NAME@ as a shared library." ON)
if(BUILD_SHARED_LIBS)
  set(LIBRARY_TYPE SHARED)
else()
  set(LIBRARY_TYPE STATIC)
endif()

# Target
add_library(${BIOSMABE_LIBS} ${LIBRARY_TYPE} ${SOURCES} ${HEADERS})
target_link_libraries(${BIOSMABE_LIBS} ${OpenCV_LIBS})

# Install library
install(TARGETS ${BIOSMABE_LIBS}
  EXPORT ${PROJECT_EXPORT}
  RUNTIME DESTINATION "${INSTALL_BIN_DIR}" COMPONENT bin
  LIBRARY DESTINATION "${INSTALL_LIB_DIR}" COMPONENT shlib
  ARCHIVE DESTINATION "${INSTALL_LIB_DIR}" COMPONENT stlib
  COMPONENT dev)
  
# Create 'version.h'
configure_file(version.h.in
  "${CMAKE_CURRENT_BINARY_DIR}/version.h" @ONLY)
set(HEADERS ${HEADERS} ${CMAKE_CURRENT_BINARY_DIR}/version.h)

# Install headers
install(FILES ${HEADERS}
  DESTINATION "${INSTALL_INCLUDE_DIR}/${LIBRARY_FOLDER}" )

  
# Set Output directories
set(CMAKE_DEBUG_POSTFIX _d)
set_target_properties( ${BIOSMABE_LIBS}
    PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin"
	DEBUG_POSTFIX			 "${CMAKE_DEBUG_POSTFIX}"
)